# Generated by Django 5.2.4 on 2025-12-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_generateddocument_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='doc_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
