# Generated by Django 5.2.4 on 2025-12-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0003_workschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='daily_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='weekly_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_days_per_week',
        ),
    ]
