# Generated by Django 5.2.4 on 2025-12-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0004_remove_employee_daily_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='has_paid_weekly_holiday',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_severance_eligible',
        ),
    ]
