# Generated by Django 5.2.4 on 2025-12-15 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0005_remove_employee_has_paid_weekly_holiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_schedules', to='labor.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'year', 'month'], name='labor_month_employe_89436b_idx')],
                'unique_together': {('employee', 'year', 'month', 'weekday')},
            },
        ),
    ]
