# Generated by Django 5.2.4 on 2025-12-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0006_monthlyschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='end_date',
        ),
    ]
