# Generated by Django 5.2.4 on 2025-12-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0007_remove_employee_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('annual', '연차'), ('sick', '병가'), ('personal', '개인사유')], default='annual', max_length=20)),
                ('days', models.DecimalField(decimal_places=1, default=1.0, help_text='사용 일수 (0.5=반차, 1=연차)', max_digits=3)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_usages', to='labor.employee')),
            ],
            options={
                'ordering': ['-leave_date'],
                'unique_together': {('employee', 'leave_date', 'leave_type')},
            },
        ),
    ]
