# Generated by Django 5.2.4 on 2025-12-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0008_leaveusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='workplace_address',
        ),
    ]
