# Generated by Django 5.2.4 on 2025-12-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0009_remove_employee_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='default_break_minutes_by_weekday',
            field=models.JSONField(blank=True, help_text='{0: 60, 1: 30, ...}', null=True),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='weekly_rest_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='attendance_type',
            field=models.CharField(choices=[('WORKED', '근무'), ('APPROVED_LEAVE', '승인된 휴무'), ('ABSENT', '결근')], default='WORKED', max_length=20),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='break_intervals',
            field=models.JSONField(blank=True, help_text="[{'start': ISO8601, 'end': ISO8601}, ...]", null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='day_type',
            field=models.CharField(choices=[('NORMAL', '일반근무'), ('HOLIDAY_WORK', '휴일근무')], default='NORMAL', max_length=20),
        ),
    ]
