# Generated by Django 5.2.4 on 2025-12-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0010_monthlyschedule_default_break_minutes_by_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrecord',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='break_intervals',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='break_start',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_workplace_over_5',
            field=models.BooleanField(default=False, help_text='5인 이상 사업장 여부'),
        ),
    ]
