# Generated by Django 5.2.4 on 2025-12-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0011_remove_workrecord_break_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyschedule',
            name='is_overnight',
            field=models.BooleanField(default=False, help_text='퇴근 시간이 자정(24:00)을 넘는 경우'),
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='next_day_work_minutes',
            field=models.IntegerField(default=0, help_text='익일 추가 근무 시간 (0~360분)'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='is_overnight',
            field=models.BooleanField(default=False, help_text='퇴근 시간이 자정(24:00)을 넘는 경우'),
        ),
        migrations.AddField(
            model_name='workrecord',
            name='next_day_work_minutes',
            field=models.IntegerField(default=0, help_text='익일 추가 근무 시간 (0~360분, 24:00~06:00 구간)'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='is_overnight',
            field=models.BooleanField(default=False, help_text='퇴근 시간이 자정(24:00)을 넘는 경우'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='next_day_work_minutes',
            field=models.IntegerField(default=0, help_text='익일 추가 근무 시간 (0~360분)'),
        ),
    ]
