# Generated by Django 5.2.4 on 2025-12-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0012_monthlyschedule_is_overnight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyschedule',
            name='default_break_minutes_by_weekday',
        ),
        migrations.AddField(
            model_name='monthlyschedule',
            name='break_minutes',
            field=models.IntegerField(default=0, help_text='휴게 시간 (분)'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_minutes',
            field=models.IntegerField(default=0, help_text='휴게 시간 (분)'),
        ),
    ]
