# Generated by Django 5.2.4 on 2025-12-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0013_remove_monthlyschedule_default_break_minutes_by_weekday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecord',
            name='attendance_status',
            field=models.CharField(choices=[('REGULAR_WORK', '근무(소정근로)'), ('EXTRA_WORK', '추가근무'), ('ANNUAL_LEAVE', '연차사용'), ('ABSENT', '결근'), ('SICK_LEAVE', '병가')], default='REGULAR_WORK', help_text='출결 상태 (소정근로/추가근무/연차/결근/병가)', max_length=20),
        ),
    ]
