# Generated by Django 5.2.4 on 2025-12-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0014_add_attendance_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, default='알바', max_length=50),
        ),
    ]
