# Generated by Django 5.2.4 on 2025-12-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0015_alter_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_weekly_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='계약상 주 소정근로시간', max_digits=4, null=True),
        ),
    ]
