# Generated by Django 5.2.4 on 2025-12-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0016_employee_contract_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deduction_type',
            field=models.CharField(choices=[('NONE', '미선택 (세전)'), ('FOUR_INSURANCE', '4대보험'), ('FREELANCE', '3.3% (프리랜서)')], default='NONE', help_text='급여 공제 방식', max_length=20),
        ),
    ]
